apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.8.3
    helm:
      values: |
        controller:
          # Enable metrics for Prometheus scraping
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                app: nginx-ingress
            prometheusRule:
              enabled: true
              additionalLabels:
                app: nginx-ingress
          
          # Resource limits
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
            limits:
              cpu: 500m
              memory: 500Mi
          
          # Enable additional metrics
          config:
            enable-opentracing: "true"
            log-format-escape-json: "true"
            log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
          
          # Service configuration
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: nlb
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          
          # Enable admission webhooks for better validation
          admissionWebhooks:
            enabled: true
            
        # Enable default backend for 404 handling
        defaultBackend:
          enabled: true
          image:
            repository: k8s.gcr.io/defaultbackend-amd64
            tag: "1.5"
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 30Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
