# apps/monitoring/prometheus/values.yaml

grafana:
  enabled: true
  adminPassword: "admin"  # Change this for security
  service:
    type: NodePort
  ingress:
    enabled: false

prometheus:
  service:
    type: NodePort

# Optional alertmanager config
alertmanager:
  enabled: true
  service:
    type: NodePort
