defaultRules:
  create: true

grafana:
  enabled: true
  adminUser: admin
  adminPassword: securepassword123
  service:
    type: ClusterIP

prometheus:
  enabled: true
  service:
    type: ClusterIP

alertmanager:
  enabled: false
