apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.10
    helm:
      values: |
        loki:
          enabled: true
        promtail:
          enabled: false
        grafana:
          enabled: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
